### PR TITLE
[app-editors/texworks] initial import of version 0.4.6

### PR DESCRIPTION
**Pull request by hasufell**
Not really sure if this is the right place, but "office-overlay" sounds generic enough. Maybe if there was a tex/latex overlay I'd dump it there.

### CODE REVIEW

**Comment by yurats** [comment]
configure fails, whena I try USE="qt5 -qt4" emerge texworks.
build log: http://pastebin.com/7eaGrGdG
emerge --info: http://pastebin.com/XvU1jwUB

**Comment by hasufell** [comment]
yep, I haven't tested qt5, can you make it work?

**Comment by akhuettel** [comment]
Doesnt make too much sense here, we use the overlay only for libreoffice and its close friends. My suggestion would be to add it to the main tree.

**Comment by hasufell** [comment]
The main tree slows down contribution workflow a lot. Unless I use a package myself, I'll not add anything there.

Upgrading this repository with a contribution workflow makes sense IMO, since there really is no appropriate office overlay anywhere.

**Comment by hasufell** [comment]
@akhuettel so I already have one user pull request, seems there is demand after all for an office-themed overlay, don't you think?

**Comment by hasufell** [comment]
@yurats since the overlay maintainer ignores us, I guess we can just setup up our own office overlay instead and add it to layman

**Pull request closed without merging**
